### ISSUE TITLE
Missing ! on date.php file

### ISSUE THREAD

**Issue by doonmok** [Fastspot/bigtree-form-builder#16]
The templates/routed/btx-form-builder/field-types/draw/date.php file on line 17 should be !empty not empty. 

Currently
if (empty($field_data["required"])) {

Should be
if (!empty($field_data["required"])) {

**Comment by timbuckingham** [comment]
Thanks, Doon! Just pushed a fix for this to 2.6.1.

**Comment by doonmok** [comment]
Thank you!
