### ISSUE TITLE
Upload does not show what extensions are allowed. 

### ISSUE THREAD

**Issue by doonmok** [Fastspot/bigtree-form-builder#17]
The upload field does not show what extensions are allowed. 
\templates\routed\btx-form-builder\field-types\draw\upload.php

On line 22, the if statement does not seem to work. I think the empty function won't work with an associative array. 

!empty($field_data["allowed_fieldtypes"])

**Comment by doonmok** [comment]
Tim, I think I figured out the issue. On line 22, it should be 

!empty($field_data["allowed_filetypes"]
instead of
!empty($field_data["allowed_fieldtypes"]

_filetypes instead of _fieldtypes

\templates\routed\btx-form-builder\field-types\draw\upload.php

**Comment by timbuckingham** [comment]
Good catch! I've pushed up Form Builder 2.7.1 that fixes this. Sorry for the long delay on this fix.
