### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by jefe317** [Fastspot/bigtree-form-builder#8]
There is an error message that gets displayed if users don't fill out all required fields.
The current message is "Required fields were missing. Please fill out all required fields **out** and submit again." and should probably read "Required fields were missing. Please fill out all required fields and submit again."
It looks like this is on line 34 & 36 on default.php

**Comment by timbuckingham** [comment]
Thanks! I just pushed a fix for this, I'm making a few other form builder updates and this should be out in the next release.
